# Generated by Django 2.1.15 on 2020-06-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Total', models.IntegerField()),
                ('Recovered', models.IntegerField()),
                ('Death', models.IntegerField()),
            ],
        ),
    ]
